--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: ezugworie
--

CREATE TABLE public.actors (
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer NOT NULL,
    gender character varying NOT NULL
);


ALTER TABLE public.actors OWNER TO ezugworie;

--
-- Name: actors_id_seq; Type: SEQUENCE; Schema: public; Owner: ezugworie
--

CREATE SEQUENCE public.actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actors_id_seq OWNER TO ezugworie;

--
-- Name: actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ezugworie
--

ALTER SEQUENCE public.actors_id_seq OWNED BY public.actors.id;


--
-- Name: movie_casts; Type: TABLE; Schema: public; Owner: ezugworie
--

CREATE TABLE public.movie_casts (
    id integer NOT NULL,
    actor_id integer NOT NULL,
    movie_id integer NOT NULL
);


ALTER TABLE public.movie_casts OWNER TO ezugworie;

--
-- Name: movie_casts_id_seq; Type: SEQUENCE; Schema: public; Owner: ezugworie
--

CREATE SEQUENCE public.movie_casts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movie_casts_id_seq OWNER TO ezugworie;

--
-- Name: movie_casts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ezugworie
--

ALTER SEQUENCE public.movie_casts_id_seq OWNED BY public.movie_casts.id;


--
-- Name: movies; Type: TABLE; Schema: public; Owner: ezugworie
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    title character varying NOT NULL,
    release_date timestamp without time zone NOT NULL
);


ALTER TABLE public.movies OWNER TO ezugworie;

--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: ezugworie
--

CREATE SEQUENCE public.movies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movies_id_seq OWNER TO ezugworie;

--
-- Name: movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ezugworie
--

ALTER SEQUENCE public.movies_id_seq OWNED BY public.movies.id;


--
-- Name: actors id; Type: DEFAULT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.actors ALTER COLUMN id SET DEFAULT nextval('public.actors_id_seq'::regclass);


--
-- Name: movie_casts id; Type: DEFAULT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.movie_casts ALTER COLUMN id SET DEFAULT nextval('public.movie_casts_id_seq'::regclass);


--
-- Name: movies id; Type: DEFAULT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.movies ALTER COLUMN id SET DEFAULT nextval('public.movies_id_seq'::regclass);


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: ezugworie
--

COPY public.actors (id, name, age, gender) FROM stdin;
1	Harrison Ezgels	36	Male
7	Kevin Hart	42	Male
8	Rowan Atkinson	67	Male
9	Angelina Jolie	47	Female
10	Nicholas Cage	58	Male
\.


--
-- Data for Name: movie_casts; Type: TABLE DATA; Schema: public; Owner: ezugworie
--

COPY public.movie_casts (id, actor_id, movie_id) FROM stdin;
1	1	1
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: ezugworie
--

COPY public.movies (id, title, release_date) FROM stdin;
1	A Broken Rose	2023-06-12 00:00:00
7	Ghost Doctor	2020-01-16 13:40:00
8	Glamour Girls	2018-01-16 13:40:00
9	Man vs Bee	2023-01-25 15:20:00
10	Osuofia in London	2016-03-10 22:15:00
\.


--
-- Name: actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ezugworie
--

SELECT pg_catalog.setval('public.actors_id_seq', 10, true);


--
-- Name: movie_casts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ezugworie
--

SELECT pg_catalog.setval('public.movie_casts_id_seq', 1, true);


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ezugworie
--

SELECT pg_catalog.setval('public.movies_id_seq', 10, true);


--
-- Name: actors actors_name_key; Type: CONSTRAINT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_name_key UNIQUE (name);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: movie_casts movie_casts_pkey; Type: CONSTRAINT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.movie_casts
    ADD CONSTRAINT movie_casts_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- Name: movies movies_title_key; Type: CONSTRAINT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_title_key UNIQUE (title);


--
-- Name: movie_casts movie_casts_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.movie_casts
    ADD CONSTRAINT movie_casts_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actors(id);


--
-- Name: movie_casts movie_casts_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: ezugworie
--

ALTER TABLE ONLY public.movie_casts
    ADD CONSTRAINT movie_casts_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(id);


--
-- PostgreSQL database dump complete
--

